USE pizzaria_db;

ALTER TABLE pedido
MODIFY status ENUM('REGISTRADO','PREPARANDO','EM_ROTA','ENTREGUE','FINALIZADO') DEFAULT 'REGISTRADO';

ALTER TABLE pedido_status_historico
MODIFY status ENUM('REGISTRADO','PREPARANDO','EM_ROTA','ENTREGUE','FINALIZADO');
